PreCommit:
  RuboCop:
    enabled: true
    command:
      - bundle
      - exec
      - rubocop

  Fasterer:
    enabled: true
    command:
      - bundle
      - exec
      - fasterer

  Reek:
    enabled: true
    # command:
      # - bundle
      # - exec
      # - reek
    command: ['/usr/local/bin/bundle', 'exec', 'reek']

  RSpec:
    enabled: true
    command:
      - bundle
      - exec
      - rspec
      - --fail-fast

  Brakeman:
    enabled: true
    command:
      - bundle
      - exec
      - brakeman
      - --quiet
      - --no-pager

  BundlerAudit:
    enabled: true
    command:
      - bundle
      - exec
      - bundler-audit
      - check

PrePush:
  RSpec:
    enabled: true
    command:
      - bundle
      - exec
      - rspec
      - --fail-fast

PostMerge:
  RuboCop:
    enabled: true
    command:
      - bundle
      - exec
      - rubocop
