require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/floors", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Floor. As you add validations to Floor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Floor.create! valid_attributes
      get floors_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      floor = Floor.create! valid_attributes
      get floor_url(floor)
      expect(response).to be_successful
    end
  end

  # describe "GET /new" do
  #   it "renders a successful response" do
  #     get new_floor_url
  #     puts response.status
  #     puts response.body
  #     expect(response).to be_successful
  #   end
  # end

  describe "GET /edit" do
    it "renders a successful response" do
      floor = Floor.create! valid_attributes
      get edit_floor_url(floor)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Floor" do
        expect {
          post floors_url, params: { floor: valid_attributes }
        }.to change(Floor, :count).by(1)
      end

      it "redirects to the created floor" do
        post floors_url, params: { floor: valid_attributes }
        expect(response).to redirect_to(floor_url(Floor.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Floor" do
        expect {
          post floors_url, params: { floor: invalid_attributes }
        }.to change(Floor, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post floors_url, params: { floor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested floor" do
        floor = Floor.create! valid_attributes
        patch floor_url(floor), params: { floor: new_attributes }
        floor.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the floor" do
        floor = Floor.create! valid_attributes
        patch floor_url(floor), params: { floor: new_attributes }
        floor.reload
        expect(response).to redirect_to(floor_url(floor))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        floor = Floor.create! valid_attributes
        patch floor_url(floor), params: { floor: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested floor" do
      floor = Floor.create! valid_attributes
      expect {
        delete floor_url(floor)
      }.to change(Floor, :count).by(-1)
    end

    it "redirects to the floors list" do
      floor = Floor.create! valid_attributes
      delete floor_url(floor)
      expect(response).to redirect_to(floors_url)
    end
  end
end
