services:
  web:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ..
        target: /workspace
      - ..:/app:cached
      - bundle_cache:/usr/local/bundle
      - ${SSH_AUTH_SOCK}:/ssh-agent
      - bootsnap_cache:/app/tmp/cache
    working_dir: /workspace
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      PORT: 3000
      RAILS_MAX_THREADS: 5
      RAILS_MIN_THREADS: 1
      WEB_CONCURRENCY: 0
      SSH_AUTH_SOCK: /ssh-agent

volumes:
  bundle_cache:
  bootsnap_cache: